language: java
before_install:
  - chmod +x gradlew
jdk:
  - openjdk8
script:
  - jdk_switcher use openjdk8
  - export JAVA_HOME=$HOME/openjdk8
  - java $JAVA_OPTS -jar admin/build/libs/admin-1.0-SNAPSHOT.jar --port $PORT web/*.war
addons:
  apt:
    packages:
      - oracle-java8-installer

