language: java
before_install:
  - chmod +x gradlew
jdk:
  - openjdk8
script:
  - jdk_switcher use openjdk8
  - export JAVA_HOME=$HOME/openjdk8
  - java -jar build/server/webapp-runner-*.jar build/libs/*.war
  #-jar admin/build/libs/admin-1.0-SNAPSHOT.jar
addons:
  apt:
    packages:
      - oracle-java8-installer

