language: java
before_install:
  - chmod +x gradlew
jdk:
  - openjdk8
script:
  - jdk_switcher use openjdk8
  - ./gradlew copyToLib
  - java -jar web/build/server/webapp-runner-*.jar web/build/libs/*.war
apt:
   packages:
     - oracle-java8-installer
deploy:
   provider: heroku
     api_key:
       secure: 8ed19f67-3834-4188-ad4c-142e60321123

