language: java
jdk:
  - openjdk8
script:
  - jdk_switcher use openjdk8
  - export JAVA_HOME=$HOME/openjdk8
  - $TRAVIS_BUILD_DIR/install-jdk.sh --install openjdk11 --traget $JAVA_HOME
  - java $JAVA_OPTS -jar admin/build/libs/admin-1.0-SNAPSHOT.jar --port $PORT web/*.war
