language: java
before_install:
  - chmod +x gradlew
jdk:
  - openjdk8
script:
  - jdk_switcher use openjdk8
  #- export JAVA_HOME=$HOME/openjdk8
  - ./gradlew copyToLib
  - java -jar web/build/server/webapp-runner-*.jar web/build/libs/*.war
apt:
   packages:
     - oracle-java8-installer

